name: Terraform Cloud Run Action
author: Koenraad Verheyden
description: Create and customize a run on Terraform Cloud

branding:
  icon: fast-forward
  color: purple

inputs:
  terraform-host:
    description: |
     The address of the terraform Enterprise API
    required: false
    default: 'https://app.terraform.io'
  token:
    description: |
      Token used to communicating with the Terraform Cloud API. Must be a user or team api token.
    required: true
  organization:
    description: |
      Name of the organization on Terraform Cloud, defaults to the owner of the GitHub repository.
    required: false
    default: ${{ github.repository_owner }}
  workspace:
    description: >
      Name of the workspace on Terraform Cloud.
    required: true
  speculative:
    description: |
      Whether to run a speculative plan.
    required: false
    default: 'false'
    deprecationMessage: |
      The property speculative is deprecated in favor of type. If type is set, speculative is ignored.
  type:
    description: |
      The type of run, allowed options are 'plan', 'apply' and 'destroy'.
    required: false
    default: 'apply'
  targets:
    description: |
      An optional list of resource addresses to target. Should be list separated by newlines.
    required: false
    default: ''
  wait-for-completion:
    description: |
      Whether we should wait for the plan or run to be applied. This will block until the run is finished. Defaults to true.
    required: false
    default: 'true'
  message:
    description: |
      Optional message to use as name of the run.
    required: false
    default: 'Queued by GitHub Actions (commit: ${{ github.sha }})'
  directory:
    description: |
      The directory that is uploaded to Terraform Enterprise, defaults to repository root. Respects .terraformignore.
    required: false
  tf-vars:
    description: |
      The contents of a auto.tfvars file that will be uploaded to Terraform Cloud.
    required: false

outputs:
  run-url:
    description: URL of the run on Terraform Cloud.
  has-changes:
    description: Whether a speculative plan has changes or not.

  # tfe-run will also output all outputs from the Terraform workspace prefixed
  # with `tf-`. Since these are dynamic, they can't be listed in action.yaml.
  # For example, if a workspace has an output `endpoint`, this will exported by
  # tfe-run as `tf-endpoint`.

runs:
  using: docker
  image: Dockerfile
